# Generated by Django 5.2.4 on 2025-08-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('our_score', models.IntegerField(blank=True, help_text='The score of the EVSU team.', null=True)),
                ('opponent_score', models.IntegerField(blank=True, help_text='The score of the opponent.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('EXCUSED', 'Excused')], default='REGISTERED', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Reason for absence, etc.', null=True)),
            ],
        ),
    ]
