# Generated by Django 5.2.4 on 2025-08-25 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0001_initial'),
        ('coaches', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='coach_in_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_events', to='coaches.coach'),
        ),
        migrations.AddField(
            model_name='participationlog',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.athlete'),
        ),
        migrations.AddField(
            model_name='participationlog',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='attended_events', through='events.ParticipationLog', to='athletes.athlete'),
        ),
        migrations.AlterUniqueTogether(
            name='participationlog',
            unique_together={('event', 'athlete')},
        ),
    ]
