# Generated by Django 5.2.4 on 2025-08-25 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='statistic',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='core.sport'),
        ),
        migrations.AddField(
            model_name='team',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campus'),
        ),
        migrations.AddField(
            model_name='team',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sport'),
        ),
        migrations.AlterUniqueTogether(
            name='statistic',
            unique_together={('sport', 'short_name')},
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('sport', 'campus', 'gender')},
        ),
    ]
