# Generated by Django 5.2.4 on 2025-11-16 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='denominator',
            field=models.ForeignKey(blank=True, help_text="The 'Attempted' part of a formula (e.g., '2-Pointers Attempted').", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denominator_for', to='core.statistic'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='numerator',
            field=models.ForeignKey(blank=True, help_text="The 'Made' part of a formula (e.g., '2-Pointers Made').", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='numerator_for', to='core.statistic'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='stat_type',
            field=models.CharField(choices=[('INPUT', 'User Input'), ('CALCULATED', 'Calculated')], default='INPUT', max_length=10),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='name',
            field=models.CharField(help_text="The full, user-facing name of the statistic (e.g., '2-Point Percentage')", max_length=100),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='short_name',
            field=models.CharField(help_text="A short, unique code for this stat used internally (e.g., '2pt_pct')", max_length=20),
        ),
    ]
