# Generated by Django 5.2.4 on 2025-11-16 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_statistic_denominator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='denominator',
            field=models.ForeignKey(blank=True, help_text="For calculated stats, this is the denominator (e.g., 'Field Goals Attempted').", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denominator_for', to='core.statistic'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='is_calculated',
            field=models.BooleanField(default=False, help_text='Check if this is a calculated stat (e.g., a percentage).'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='numerator',
            field=models.ForeignKey(blank=True, help_text="For calculated stats, this is the numerator (e.g., 'Field Goals Made').", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='numerator_for', to='core.statistic'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='name',
            field=models.CharField(help_text="The full, user-facing name of the statistic (e.g., 'Points Per Game' or 'Field Goal %').", max_length=100),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='short_name',
            field=models.CharField(help_text="A short, unique code for this stat used internally (e.g., 'ppg' or 'fg_pct').", max_length=20),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='sport',
            field=models.ForeignKey(blank=True, help_text='The sport this stat belongs to. Leave blank for universal stats like Wins/Losses.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='core.sport'),
        ),
    ]
