# Generated by Django 5.2.4 on 2025-11-16 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_statistic_denominator_statistic_is_calculated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='denominator',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='is_calculated',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='numerator',
        ),
        migrations.AlterField(
            model_name='statistic',
            name='name',
            field=models.CharField(help_text="The full name of the statistic (e.g., 'Points Per Game')", max_length=100),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='short_name',
            field=models.CharField(help_text="A short, unique code for this stat (e.g., 'ppg')", max_length=20),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='core.sport'),
        ),
    ]
