# Generated by Django 5.2.4 on 2025-11-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_statistic_denominator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='formula',
            field=models.CharField(blank=True, help_text="For Derived stats only. Use short_names of other stats. e.g., 'fgm / fga * 100'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='stat_type',
            field=models.CharField(choices=[('SIMPLE', 'Simple Input'), ('DERIVED', 'Derived (Calculated)')], default='SIMPLE', help_text='Is this a stat you enter directly, or one that is calculated automatically?', max_length=10),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='name',
            field=models.CharField(help_text="The full, user-friendly name of the statistic (e.g., 'Points Per Game')", max_length=100),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='short_name',
            field=models.CharField(help_text="A short, unique code for this stat used in formulas (e.g., 'ppg')", max_length=20),
        ),
    ]
