# Generated by Django 5.2.4 on 2025-08-25 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coaches', '0001_initial'),
        ('core', '0002_initial'),
        ('events', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('medical_history', models.TextField(blank=True, null=True)),
                ('contact_details', models.CharField(max_length=255)),
                ('is_featured', models.BooleanField(default=False)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coaches.coach')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.team')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_stats', to='athletes.athlete')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_stats', to='events.event')),
                ('statistic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.statistic')),
            ],
            options={
                'unique_together': {('athlete', 'statistic', 'event')},
            },
        ),
    ]
